// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwjFkCH0JczSMe__lBzp9wDe9qg-_-xs',
    appId: '1:438699557837:web:31c017172caddb5ea27a84',
    messagingSenderId: '438699557837',
    projectId: 'flutter-deliveryfood',
    authDomain: 'flutter-deliveryfood.firebaseapp.com',
    storageBucket: 'flutter-deliveryfood.appspot.com',
    measurementId: 'G-RW1QJQZSGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZPMSuxyQp22F7mzjFkFOBxlp9bnEpUA',
    appId: '1:438699557837:android:d2946cf94a05c2ada27a84',
    messagingSenderId: '438699557837',
    projectId: 'flutter-deliveryfood',
    storageBucket: 'flutter-deliveryfood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgAOogeyxnQAqOL0QP6EGBgc6Yxg9aQM',
    appId: '1:438699557837:ios:f7e430133bc70955a27a84',
    messagingSenderId: '438699557837',
    projectId: 'flutter-deliveryfood',
    storageBucket: 'flutter-deliveryfood.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgAOogeyxnQAqOL0QP6EGBgc6Yxg9aQM',
    appId: '1:438699557837:ios:f7e430133bc70955a27a84',
    messagingSenderId: '438699557837',
    projectId: 'flutter-deliveryfood',
    storageBucket: 'flutter-deliveryfood.appspot.com',
    iosBundleId: 'com.example.foody',
  );
}
